Fix impossible if condition
tsbischof/libpicoquant pull request #24
Opened 2024-02-23 14:27 UTC by T0mstone

I'm not sure what the original intent was, but the if condition here could never be true.

For example, assume `magic = "PQHISTO"`. Then, the if condition would evaluate to `( ! false || ! true )`,
which is `( true || false )`, aka. `true`.

This PR just changes the `||` to `&&`, which I assume was the original intent.

2024-02-23 14:33 UTC, T0mstone commented
Btw, the example isn't made-up: I have a `.phu` file that starts with `PQHISTO\01.1.00`. Not sure if I can share it tho.

2024-02-23 19:44 UTC, tsbischof requested changes
The original intent of this code was to detect unified data files based on the presence of PQTTTR or PQHIST as the first 6 characters in the header. Since `strncmp` returns 0 for equality the original line would be equivalent to `magic[:6] == "PQTTTR" or magic[:6] == "PQHIST"`. It seems like your change replaces the `or` with `and`, which can never be true and would then cause a branch into interpretation of the file as a non-unifed (e.g. phd, pt2, pt3) file type. Is this correct, or have I missed something?

That said I do not have an sample data for the phu format (`PQHISTO\0`) in my collection (https://github.com/tsbischof/picoquant-sample-data). If you cannot share a full file, could you share a sanitized header? Or ideally create a shareable file for testing purposes?

The sample code I can run to read this branch:
`picoquant --file-in picoquant-sample-data/picoharp/v20_t3.ptu --header-only --verbose`

2024-02-26 16:45 UTC, T0mstone commented
Sorry, you're right. I thought my limited knowledge of C was enough to see this "issue", but I was completely in the wrong.
I feel like an idiot now; Really sorry for wasting your time with this.

As for the sample data, I'll see what I can do, but I'll probably open an issue/PR in the other repo for that.

2024-02-26 16:45 UTC, closed without merging

2024-02-26 16:59 UTC, tsbischof commented
Ah yeah no worries! I am much happier to get a few false positives from time to time than to miss critical issues.